/** @format */

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/layout/SideBar";
import Providers from "@/app/providers";
import Header from "@/components/layout/Header";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans antialiased`}>
        <Providers>
          <div className="flex">
            <SideBar />
            <Header />
            <div className="mt-28">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
